#! /bin/sh

sxhkd &

bspc monitor DP-2 -d I II III IV V 
bspc monitor DP-4 -d VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a pavucontrol state=floating

wallpapers=$HOME/pics/wallpapers/
if [ -d "$wallpapers" ]; then
    xwallpaper --stretch $wallpapers/nasa_japanese.png
fi

$HOME/.config/polybar/launch.sh
